# Generated by Django 6.0.2 on 2026-03-23 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavingsPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('savings_target_percentage', models.PositiveIntegerField(default=10)),
                ('prefer_discounted_products', models.BooleanField(default=True)),
                ('allow_generic_brands', models.BooleanField(default=True)),
                ('compare_all_stores', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savings_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User savings preference',
                'verbose_name_plural': 'User savings preferences',
            },
        ),
    ]
