# Generated by Django 6.0.2 on 2026-03-23 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grocerysaver', '0017_rename_grocerysave_user_id_f28409_idx_grocerysave_user_id_8ce979_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='current_price_sync', max_length=40)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='grocerysaver.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='grocerysaver.store')),
            ],
            options={
                'ordering': ['-captured_at', 'price'],
                'indexes': [models.Index(fields=['product', 'store', '-captured_at'], name='prices_pric_product_614c67_idx'), models.Index(fields=['store', '-captured_at'], name='prices_pric_store_i_c64cae_idx')],
            },
        ),
    ]
