# Generated by Django 6.0.2 on 2026-02-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerysaver', '0004_normalize_roles_cliente_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('apple', 'Apple')], max_length=20),
        ),
    ]
