# Generated by Django 6.0.2 on 2026-02-19 22:40

import django.db.models.deletion
from django.db import migrations, models


def seed_catalog_data(apps, schema_editor):
    Category = apps.get_model('grocerysaver', 'Category')
    Store = apps.get_model('grocerysaver', 'Store')
    Product = apps.get_model('grocerysaver', 'Product')
    ProductPrice = apps.get_model('grocerysaver', 'ProductPrice')

    stores = {}
    for name in ['Toti', 'Tia', 'Supermaxi']:
        stores[name], _ = Store.objects.get_or_create(name=name)

    categories = {}
    for name in ['Frutas', 'Verduras', 'Carnes', 'Mariscos', 'Lacteos']:
        categories[name], _ = Category.objects.get_or_create(name=name)

    product_specs = [
        ('Lacteos', 'Leche Entera 1L', '', {'Toti': '1.05', 'Tia': '2.25', 'Supermaxi': '1.95'}),
        ('Frutas', 'Manzana Roja', '', {'Toti': '0.60', 'Tia': '0.72', 'Supermaxi': '0.68'}),
        ('Verduras', 'Tomate', '', {'Toti': '0.90', 'Tia': '1.05', 'Supermaxi': '1.00'}),
        ('Carnes', 'Pechuga de Pollo 1kg', '', {'Toti': '4.95', 'Tia': '5.30', 'Supermaxi': '5.10'}),
        ('Mariscos', 'Filete de Pescado 1kg', '', {'Toti': '6.80', 'Tia': '7.25', 'Supermaxi': '6.95'}),
    ]

    for category_name, product_name, brand, prices in product_specs:
        product, _ = Product.objects.get_or_create(
            category=categories[category_name],
            name=product_name,
            brand=brand,
        )
        for store_name, price in prices.items():
            ProductPrice.objects.update_or_create(
                product=product,
                store=stores[store_name],
                defaults={'price': price},
            )


def unseed_catalog_data(apps, schema_editor):
    Category = apps.get_model('grocerysaver', 'Category')
    Store = apps.get_model('grocerysaver', 'Store')

    Category.objects.filter(name__in=['Frutas', 'Verduras', 'Carnes', 'Mariscos', 'Lacteos']).delete()
    Store.objects.filter(name__in=['Toti', 'Tia', 'Supermaxi']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('grocerysaver', '0005_alter_socialaccount_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='grocerysaver.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='grocerysaver.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='grocerysaver.store')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'name', 'brand'), name='uniq_product_by_category_name_brand'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(fields=('product', 'store'), name='uniq_price_per_product_store'),
        ),
        migrations.RunPython(seed_catalog_data, unseed_catalog_data),
    ]
