# Generated by Django 6.0.2 on 2026-02-20 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerysaver', '0006_category_store_product_productprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='categories/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])],
            ),
        ),
    ]
