# Generated by Django 6.0.2 on 2026-02-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerysaver', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
