# Generated by Django 6.0.2 on 2026-02-21 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerysaver', '0010_raffle_notificationpreference_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='grocerysaver.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='grocerysaver.store')),
            ],
            options={
                'ordering': ['offer_price', '-starts_at'],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('offer_price__lte', models.F('normal_price'))), name='offer_price_lte_normal_price'),
                    models.CheckConstraint(condition=models.Q(('ends_at__gte', models.F('starts_at'))), name='offer_ends_after_start'),
                ],
            },
        ),
    ]
