# Generated by Django 6.0.2 on 2026-02-21 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerysaver', '0011_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('code_type', models.CharField(choices=[('barcode', 'Barcode'), ('qr', 'QR')], default='barcode', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='grocerysaver.product')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
