# Generated by Django 6.0.2 on 2026-03-23 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocerysaver', '0016_userprofile_avatar'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicesensorreading',
            new_name='grocerysave_user_id_8ce979_idx',
            old_name='grocerysave_user_id_f28409_idx',
        ),
    ]
