# Generated by Django 6.0.2 on 2026-03-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerysaver', '0017_rename_grocerysave_user_id_f28409_idx_grocerysave_user_id_8ce979_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple')], max_length=20),
        ),
    ]
