# Generated by Django 6.0.2 on 2026-03-23 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grocerysaver', '0017_rename_grocerysave_user_id_f28409_idx_grocerysave_user_id_8ce979_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='grocerysaver.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires_at', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='inventory_i_user_id_d54959_idx'), models.Index(fields=['product', 'expires_at'], name='inventory_i_product_4216a1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product', 'expires_at'), name='uniq_inventory_item_user_product_expiry'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='inventory_item_quantity_gte_1')],
            },
        ),
    ]
