from django.urls import path

from .views import (
    ActiveRaffleListView,
    AdminOnlyView,
    AddressDetailView,
    AddressListCreateView,
    ApiRootView,
    CategoryListView,
    EcuadorCantonListView,
    EcuadorGeoView,
    EcuadorProvinceListView,
    LoginView,
    LogoutView,
    MeView,
    NotificationPreferenceView,
    OfferListView,
    ProductListView,
    ProductPriceComparisonView,
    ProductScanView,
    ProtectedRouteView,
    RegisterView,
    RoleChangeRequestListCreateView,
    RoleListView,
    SocialLoginView,
    StoreListView,
    VerifyEmailView,
    WeatherView,
)

urlpatterns = [
    path('', ApiRootView.as_view(), name='api-root'),
    path('auth/roles/', RoleListView.as_view(), name='auth-roles'),
    path('auth/register/', RegisterView.as_view(), name='auth-register'),
    path('auth/verify-email/', VerifyEmailView.as_view(), name='auth-verify-email'),
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('auth/logout/', LogoutView.as_view(), name='auth-logout'),
    path('auth/me/', MeView.as_view(), name='auth-me'),
    path('auth/social-login/', SocialLoginView.as_view(), name='auth-social-login'),
    path('profile/addresses/', AddressListCreateView.as_view(), name='profile-address-list-create'),
    path('profile/addresses/<int:address_id>/', AddressDetailView.as_view(), name='profile-address-detail'),
    path('profile/notifications/', NotificationPreferenceView.as_view(), name='profile-notification-preferences'),
    path('profile/role-change-requests/', RoleChangeRequestListCreateView.as_view(), name='profile-role-change-requests'),
    path('raffles/active/', ActiveRaffleListView.as_view(), name='raffle-active-list'),
    path('stores/', StoreListView.as_view(), name='store-list'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('offers/', OfferListView.as_view(), name='offer-list'),
    path('geo/ecuador/', EcuadorGeoView.as_view(), name='geo-ecuador'),
    path('geo/ecuador/provinces/', EcuadorProvinceListView.as_view(), name='geo-ecuador-provinces'),
    path('geo/ecuador/cantons/', EcuadorCantonListView.as_view(), name='geo-ecuador-cantons'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/scan/', ProductScanView.as_view(), name='product-scan'),
    path('compare-prices/', ProductPriceComparisonView.as_view(), name='compare-prices'),
    path('weather/', WeatherView.as_view(), name='weather'),
    path('protected/', ProtectedRouteView.as_view(), name='protected-route'),
    path('protected/admin-only/', AdminOnlyView.as_view(), name='protected-admin-only'),
]
