# Generated by Django 6.0.2 on 2026-03-23 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grocerysaver', '0017_rename_grocerysave_user_id_f28409_idx_grocerysave_user_id_8ce979_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchased_at', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='grocerysaver.product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_purchases', to='grocerysaver.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at', '-id'],
                'indexes': [models.Index(fields=['user', 'product', '-purchased_at'], name='products_pr_user_id_03c037_idx'), models.Index(fields=['product', '-purchased_at'], name='products_pr_product_1b6297_idx')],
            },
        ),
    ]
